# Generated by Django 2.2.8 on 2019-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('男', 'Man'), ('女', 'Woman'), ('無法告知', 'unknow')], default='請選擇', max_length=4)),
                ('account', models.EmailField(max_length=254, unique=True)),
                ('psd', models.CharField(max_length=20, unique=True)),
                ('IDNumber', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Opet',
            fields=[
                ('o_id', models.UUIDField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('男', 'Man'), ('女', 'Woman'), ('無法告知', 'unknow')], default='請選擇', max_length=200)),
                ('area', models.CharField(choices=[('基隆市', '01'), ('台北市', '02'), ('新北市', '03'), ('桃園市', '04'), ('新竹市', '05'), ('新竹縣', '06'), ('苗栗縣', '07'), ('台中市', '08'), ('彰化縣', '09'), ('南投縣', '10'), ('雲林縣', '11'), ('嘉義市', '12'), ('嘉義縣', '13'), ('台南市', '14'), ('高雄市', '15'), ('屏東縣', '16'), ('台東縣', '17'), ('花蓮縣', '18'), ('宜蘭縣', '19'), ('澎湖縣', '20'), ('金門縣', '21'), ('連江縣', '22')], default='請選擇', max_length=200)),
                ('isAdopted', models.BooleanField()),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.User')),
            ],
        ),
    ]
