# Generated by Django 2.2.8 on 2019-12-08 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opet',
            name='area',
            field=models.CharField(choices=[('01', '基隆市'), ('02', '台北市'), ('03', '新北市'), ('04', '桃園市'), ('05', '新竹市'), ('06', '新竹縣'), ('07', '苗栗縣'), ('08', '台中市'), ('09', '彰化縣'), ('10', '南投縣'), ('11', '雲林縣'), ('12', '嘉義市'), ('13', '嘉義縣'), ('14', '台南市'), ('15', '高雄市'), ('16', '屏東縣'), ('17', '台東縣'), ('18', '花蓮縣'), ('19', '宜蘭縣'), ('20', '澎湖縣'), ('21', '金門縣'), ('22', '連江縣')], default='請選擇', max_length=200),
        ),
        migrations.AlterField(
            model_name='opet',
            name='gender',
            field=models.CharField(choices=[('Man', '男'), ('Woman', '女'), ('unknow', '無法告知')], default='請選擇', max_length=200),
        ),
        migrations.AlterField(
            model_name='opet',
            name='o_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Man', '男'), ('Woman', '女'), ('unknow', '無法告知')], default='請選擇', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
