# Generated by Django 2.2.8 on 2019-12-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191208_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Man', '男'), ('Woman', '女'), ('unknow', '無法告知')], default='請選擇', max_length=6),
        ),
    ]
