# Generated by Django 2.2.8 on 2019-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191209_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='opet',
            name='pet_type',
            field=models.CharField(default='狗', max_length=10),
        ),
        migrations.AlterField(
            model_name='opet',
            name='area',
            field=models.CharField(choices=[('基隆市', '基隆市'), ('台北市', '台北市'), ('新北市', '新北市'), ('桃園市', '桃園市'), ('新竹市', '新竹市'), ('新竹縣', '新竹縣'), ('苗栗縣', '苗栗縣'), ('台中市', '台中市'), ('彰化縣', '彰化縣'), ('南投縣', '南投縣'), ('雲林縣', '雲林縣'), ('嘉義市', '嘉義市'), ('嘉義縣', '嘉義縣'), ('台南市', '台南市'), ('高雄市', '高雄市'), ('屏東縣', '屏東縣'), ('台東縣', '台東縣'), ('花蓮縣', '花蓮縣'), ('宜蘭縣', '宜蘭縣'), ('澎湖縣', '澎湖縣'), ('金門縣', '金門縣'), ('連江縣', '連江縣')], default='請選擇', max_length=200),
        ),
    ]
